name: Deploy Multiple Vite Projects to GitHub Pages

on:
  push:
    branches:
      - dev  # 或者其他触发构建的分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - link-start

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 确保使用与项目兼容的 Node.js 版本

      - name: Install dependencies
        run: npm install
        working-directory: ${{ matrix.project }}

      - name: Build project
        run: npm run build
        working-directory: ${{ matrix.project }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ matrix.project }}/dist
          destination_dir: ${{ matrix.project }}
